import Head from 'next/head'
import Image from 'next/image'
import SideBar from '../components/SideBar'
import styles from '../styles/Home.module.css'
import { useAuthState } from "react-firebase-hooks/auth";
import { auth, db } from '../firebase';
import Chatpg from '../components/Chatpg';
import Navbar from '../components/Navbar';


export default function Home() {
  const [user, loading, error] = useAuthState(auth);

  return (
    <div className={styles.container}>
      <Head>
        <title>Chatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div style={{
        display: 'flex'
      }}>
        <div className={styles.side}>
          <SideBar type={'chats'} />
        </div>
        <div className={styles.mainChat}>
          <div style={{
            backgroundColor: "#f0f2f5",
            height: '95vh',
            maxHeight: '95vh',
            display:'flex',
            alignItems:'center',
            justifyContent:'center'
          }}>
            <div>
              <div>start your chats by clicking on Name</div>
              <div style={{textAlign:'center'}}>OR</div>
              <div style={{textAlign:'center'}}>Search your friends using mail</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
